server {
    listen 80;
    server_name _;

    location /api/ {
        proxy_pass http://127.0.0.1:5702;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location / {
        proxy_pass http://127.0.0.1:5701;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
