#!/usr/bin/env python3
"""
Export HANA DDL for a schema (tables, indexes, sequences, views, procedures, functions, synonyms).

Run on a host with hdbcli and network access to HANA (e.g. deploy@app.alphafina.cn).

Notes:
- CALL GET_OBJECT_DEFINITION works for most object types.
- For OBJECT_TYPE='VIEW' in SYS.OBJECTS, GET_OBJECT_DEFINITION often fails with "unknown type"
  (mixed-case / SQL views); DDL is built from SYS.VIEWS.DEFINITION (CREATE VIEW ... AS <select>).
- For some SQLScript functions (e.g. AgentAll_*), GET_OBJECT_DEFINITION fails; use SYS.FUNCTIONS.DEFINITION.

Credentials: set HANA_PASSWORD or pass --password (avoid committing secrets).
"""
from __future__ import annotations

import argparse
import os
import sys
from typing import TextIO

from hdbcli import dbapi


def qident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def emit_header(f: TextIO, schema: str, host: str, port: int, user: str) -> None:
    f.write(
        f"-- HANA DDL export schema={schema}\n"
        f"-- Source: {host}:{port} user={user}\n"
        "-- Generated by export-hana-schema-ddl.py\n\n"
    )


def ddl_get_object_definition(cur, schema: str, object_name: str) -> str | None:
    cur.execute("CALL GET_OBJECT_DEFINITION(?, ?)", (schema, object_name))
    row = cur.fetchone()
    if not row:
        return None
    # columns: SCHEMA_NAME, OBJECT_NAME, OBJECT_TYPE, OBJECT_OID, OBJECT_CREATION_STATEMENT
    return row[4]


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--host", default=os.environ.get("HANA_HOST", "hana.sg.sapb1c.com"))
    p.add_argument("--port", type=int, default=int(os.environ.get("HANA_PORT", "30015")))
    p.add_argument("--user", default=os.environ.get("HANA_USER", "AIRO01"))
    p.add_argument("--password", default=os.environ.get("HANA_PASSWORD"))
    p.add_argument("--schema", default=os.environ.get("HANA_SCHEMA", "SBODEMOUS"))
    p.add_argument(
        "--out",
        default=None,
        help="Output .sql file (default: ./hana-ddl-<SCHEMA>.sql in cwd)",
    )
    p.add_argument(
        "--limit",
        type=int,
        default=0,
        help="If >0, export at most this many objects per type (for smoke tests)",
    )
    p.add_argument(
        "--types",
        default=None,
        help=(
            "Comma-separated OBJECT_TYPE values to export (default: all). "
            "Example: TABLE,VIEW then later SEQUENCE,INDEX,PROCEDURE,FUNCTION,SYNONYM"
        ),
    )
    args = p.parse_args()
    if not args.password:
        print("Missing password: set HANA_PASSWORD or pass --password", file=sys.stderr)
        return 2

    schema = args.schema.upper()
    out_path = args.out or os.path.abspath(f"./hana-ddl-{schema}.sql")
    err_path = out_path + ".errors.log"

    conn = dbapi.connect(args.host, args.port, args.user, args.password)
    cur = conn.cursor()

    all_types_order = [
        "SEQUENCE",
        "TABLE",
        "INDEX",
        "VIEW",
        "PROCEDURE",
        "FUNCTION",
        "SYNONYM",
    ]
    valid_types = set(all_types_order)
    if args.types:
        allowed = [x.strip().upper() for x in args.types.split(",") if x.strip()]
        if not allowed:
            print("--types must list at least one type", file=sys.stderr)
            return 2
        bad = [x for x in allowed if x not in valid_types]
        if bad:
            print(f"Unknown --types (allowed: {sorted(valid_types)}): {bad}", file=sys.stderr)
            return 2
        type_order = [t for t in all_types_order if t in allowed]
    else:
        type_order = list(all_types_order)

    with open(out_path, "w", encoding="utf-8") as f, open(err_path, "w", encoding="utf-8") as el:
        emit_header(f, schema, args.host, args.port, args.user)
        if args.types:
            f.write(f"-- Export subset: {', '.join(type_order)}\n\n")

        ph = ",".join(["?"] * len(type_order))
        cur.execute(
            f"""
            SELECT OBJECT_NAME, OBJECT_TYPE
            FROM SYS.OBJECTS
            WHERE SCHEMA_NAME = ?
              AND OBJECT_TYPE IN ({ph})
            ORDER BY OBJECT_TYPE, OBJECT_NAME
            """,
            (schema, *type_order),
        )
        rows = cur.fetchall()

        by_type: dict[str, list[str]] = {t: [] for t in type_order}
        for name, otype in rows:
            if otype in by_type:
                by_type[otype].append(name)

        if args.limit > 0:
            for t in type_order:
                by_type[t] = by_type[t][: args.limit]

        # Preload views: DEFINITION text
        view_defs: dict[str, str] = {}
        if by_type.get("VIEW"):
            cur.execute(
                """
                SELECT VIEW_NAME, DEFINITION
                FROM SYS.VIEWS
                WHERE SCHEMA_NAME = ?
                """,
                (schema,),
            )
            for vn, defn in cur.fetchall():
                view_defs[vn] = defn or ""

        # Preload functions: full CREATE text when GET_OBJECT_DEFINITION may fail
        func_defs: dict[str, str] = {}
        if by_type.get("FUNCTION"):
            cur.execute(
                """
                SELECT FUNCTION_NAME, DEFINITION
                FROM SYS.FUNCTIONS
                WHERE SCHEMA_NAME = ?
                """,
                (schema,),
            )
            for fn, defn in cur.fetchall():
                func_defs[fn] = defn or ""

        n_ok = 0
        n_err = 0

        for otype in type_order:
            names = by_type[otype]
            if not names:
                continue
            f.write(f"\n-- ========== {otype} ({len(names)}) ==========\n\n")
            for i, name in enumerate(names, 1):
                try:
                    if otype == "VIEW":
                        defn = view_defs.get(name)
                        if not defn:
                            raise RuntimeError(f"no SYS.VIEWS.DEFINITION for {name}")
                        ddl = (
                            f'CREATE VIEW {qident(schema)}.{qident(name)} AS\n'
                            f"{defn.rstrip()}\n"
                        )
                        if not ddl.endswith(";"):
                            ddl += ";"
                        f.write(ddl + "\n\n")
                    elif otype == "FUNCTION":
                        ddl = None
                        try:
                            ddl = ddl_get_object_definition(cur, schema, name)
                        except Exception:
                            ddl = func_defs.get(name)
                        if not ddl:
                            ddl = func_defs.get(name)
                        if not ddl:
                            raise RuntimeError("no DDL from GET_OBJECT_DEFINITION or SYS.FUNCTIONS")
                        f.write(ddl.rstrip() + "\n\n")
                    else:
                        ddl = ddl_get_object_definition(cur, schema, name)
                        if not ddl:
                            raise RuntimeError("empty OBJECT_CREATION_STATEMENT")
                        f.write(ddl.rstrip() + "\n\n")
                    n_ok += 1
                except Exception as e:
                    n_err += 1
                    el.write(f"{otype} {name}: {type(e).__name__}: {e}\n")
                if i % 200 == 0:
                    f.flush()
                    el.flush()

        summary = f"\n-- done: ok={n_ok} errors={n_err} (see {err_path})\n"
        f.write(summary)
        print(out_path)
        print(summary.strip())

    cur.close()
    conn.close()
    return 0 if n_err == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
